version: '3'

services:
    python:
        build:
            context: .
            dockerfile: python.dockerfile
        environment:
            - DISPLAY=${DISPLAY}
        ports:
            - 80:8000
        volumes:
            - ./:/code
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - app-network

networks:
    app-network:
        driver: bridge