version: '3'

services:
    python:
        build:
            context: .
            dockerfile: python.dockerfile
        container_name: pystd
        environment:
            - DISPLAY=${DISPLAY}
        ports:
            - 80:8000
        volumes:
            - ./:/code
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            python-app-network:
                ipv4_address: 11.0.0.8

networks:
    python-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "11.0.0.0/16"